#!/usr/bin/env bash
set -u

#
# This is a utility to checkout git repositories in a shared location (e.g. under $HOME/gits-shared) and return the path to the checkout.
# It is designed to be used in other scripts to share git checkouts across different scripts and avoid multiple checkouts of the same repository.
# It also supports reloading the checkout and clearing it if it is invalid.
# Usage: git-shared-checkout [--reload|--clear] [--quiet] <repo_path> [--ref=<ref>]   | --version
#    eg: cat "$(git-shared-checkout https://github.com/Mac-H/ukko_gists)/readme.md"
#
# It needs to be possible to run without any other libraries (e.g. in a fresh docker image) and it should not produce any output on stdout except the path to the checkout (and error messages on stderr if needed).
#

if [[ -z "${HOME:-}" ]] ; then
    SHARED_GIT_DIR="/usr/share/gits-shared"
    SHARED_GIT_DIR_DISPLAY="/usr/share/gits-shared"
else
    SHARED_GIT_DIR="${HOME}/gits-shared"
     # shellcheck disable=SC2088
    SHARED_GIT_DIR_DISPLAY='~/gits-shared'
fi

echo "git-shared-checkout: [$*]" >&2

APP_VERSION="v0.0.6"
APP_SELF_INSTALL='yes'
function app_help()
{
    echo -e "$EXE_NAME: Checkout a git repository to the shared location ${COLOUR[VIVID_BLUE_STDOUT]:-}${SHARED_GIT_DIR_DISPLAY}${COLOUR[OFF_STDOUT]:-} and return the path to the checkout."

    echo -e "Usage: $EXE_NAME [--reload|--clear] [options] <repo_path> [--ref=<ref>]"
    echo -e "       <ref> = hash:###      -or-"
    echo -e "               branch:###    -or-"
    echo -e "               tag:###       -or-"
    echo -e "               ver:###        (The first found of: [tag:###,branch:###,branch:###-wip]) -or-"
    echo -e "               hash-only:###  (No git history - only download the files)"
    echo -e "Other options:"
    echo -e "       --reload           Clear the checkout and reload it from the repository (if it already exists)"
    echo -e "       --clear            Clear the checkout without reloading it (if it already exists)"
    echo -e "       --quiet=yes/no     Suppress informational messages (warnings and errors will still be shown)"
    #echo -e
    echo -e "   eg: ${COLOUR[VIVID_BLUE_STDOUT]:-}cat \"\$($EXE_NAME https://github.com/Mac-H/ukko_gists)/readme.md\"${COLOUR[OFF_STDOUT]:-}"
    echo -e ""
    echo -e " -or-  $EXE_NAME [--list]"
}


####################################
# Custom load of parameters:
#
#    Value                 Default
#    --------------------  ----------------
#  * option_is_reload      'no'
#  * option_is_erase       'no'
#  * option_is_quiet       'yes-unless-info'
#  * option_ref_type       ''
#  * option_ref_value      ''
#  * option_repo_url       ''
#
# These are called from load_params and should not be called directly.
#
#  * app_load_param 'all-defaults'       - Load all default values for options
#  * app_load_param 'option-arg' <arg>   - Load an option from an argument (e.g. --reload, --ref=branch:main)
#  * app_load_param 'direct-arg' <arg>   - Load a direct argument (e.g. the repo URL)
#
function app_load_param_defaults()
{
    option_is_reload='no'
    option_is_erase='no'
    option_is_quiet='yes-unless-info'

    option_ref_type=''
    option_ref_value=''
    option_repo_url=''
    option_list_shared_checkouts='no'
    [[ "${GIT_SHARED_CHECKOUT_QUIET:-}" == "yes" ]] && option_is_quiet='yes'
}

function app_load_param_direct_value()
{
    local arg="${1}"
    #
    # Direct arguments  (Typically not starting with - or --.  However if '--' is provided, then all subsequent arguments are treated as direct arguments even if they start with - or --)
    #
    if [[ "$arg" == 'branch:'* ]]; then
        option_ref_type='branch'
        option_ref_value="${arg#branch:}"
        giveWarning "Deprecated used of ${arg} :  Use --ref=${arg} instead"
    elif [[ -z "$option_repo_url" ]]; then
        option_repo_url="$arg"
    else
        do_errorExitWithSuggestion "Multiple repository URLs provided.  Already have ${option_repo_url@Q} but adding '${arg@Q}' is an error."
    fi
}

function app_load_param_option_name_value()
{
    local name="${1}"
    local value="${2:-}"

    #
    # Option arguments  (Typically of the form '-n', '--name' or '--name=value')
    #
    if [[   "$name" == '--list'    ]] ; then   option_list_shared_checkouts=yes
    elif [[ "$name" == '--reload'  ]] ; then   option_is_reload='yes'
    elif [[ "$name" == '--clear'   ]] ; then   option_is_erase='yes'
    elif [[ "$name" == '--quiet'   ]] ; then   option_is_quiet='yes'
    elif [[ "$name" == '--quiet='  ]] ; then
        app_load_param_validate_from_list "$name" "$value" "yes,no,yes-unless-info"
        option_is_quiet="$value"
    elif [[ "$name" == '--ref=' ]]; then
        ref_arg="${value}"
        if [[ "$ref_arg" == '#'* ]]; then
            option_ref_type='hash'
            option_ref_value="${ref_arg#\#}"
            giveWarning "Deprecated used of --ref=#${option_ref_value} :  Use --ref=hash:${option_ref_value} instead"
        elif [[ -n "$ref_arg" ]]; then
            for x in hash hash-only branch tag ver ; do
                if [[ "$ref_arg" == "$x:"* ]]; then
                    option_ref_type="$x"
                    option_ref_value="${ref_arg#"$x:"}"
                    break
                fi
            done
            [[ -z "$option_ref_type" ]] && do_errorExitWithSuggestion "Invalid format for \`$name=$value\` : Expected --ref=branch:<branch_name> or --ref=tag:<tag_name> or --ref=hash:<hash_value> or --ref=hash-only:<hash_value> or --ref=ver:<version>"
        fi
    else
        return 1
    fi

    return 0
}


##############################################
#
# Load:
#
#    Value                 Default
#    --------------------  ----------------
#  * option_is_reload      'no'
#  * option_is_erase       'no'
#  * option_is_quiet       'yes-unless-info'
#  * option_ref_type       ''
#  * option_ref_value      ''
#  * option_repo_url       ''


function app_run()
{

    if [[ "$option_list_shared_checkouts" == "yes" ]] ; then
        doListSharedCheckouts
        [[ -n "$option_repo_url" ]] || return 0
    fi

    [[ -n "$option_repo_url" ]] || do_errorExitWithSuggestion "Expected Repository URL or --list"



    ##############################################
    #
    # Load:
    #  * repo_friendlyName
    #  * repo_fullDir
    #
    repo_friendlyName="${option_repo_url%.git}"
    if [[ "$repo_friendlyName" == "https://"* ]] ; then
        repo_friendlyName="${repo_friendlyName##https://}"
    elif [[ "$repo_friendlyName" == "git@"*     ]] ; then
        repo_friendlyName="${repo_friendlyName##git@}"
    fi

    repo_fullDir="${SHARED_GIT_DIR%/}/${repo_friendlyName/://}"

    ##############################################
    # Handle ver:
    # (The first found of: [tag:###,branch:###,branch:###-wip])
    if [[ "$option_ref_type" == "ver" ]] ; then
        if [[ -d "${repo_fullDir%/}/tag_${option_ref_value}" ]] ; then
            option_ref_type='tag'
        else
            # shellcheck disable=SC2016
            readarray -t _revMarkers < <(git ls-remote  "$option_repo_url") || do_errorExitWithSuggestion "Unable to access repository '$option_repo_url'"

            function _findRef()
            {
                local suffix="$1"
                for ref in "${_revMarkers[@]}" ; do
                    [[ "$ref" == *"refs/${suffix}" ]] && return 0
                done
                return 1
            }

            if _findRef "tags/${option_ref_value}" ; then
                option_ref_type='tag'
                echo "ℹ️  Found ${option_ref_type}: ${option_ref_value}" >&2
            elif _findRef "heads/${option_ref_value}" ; then
                option_ref_type='branch'
                echo "ℹ️  Found ${option_ref_type}: ${option_ref_value}" >&2
            elif _findRef "heads/${option_ref_value}-wip" ; then
                option_ref_type='branch'
                option_ref_value="${option_ref_value}-wip"
                echo "ℹ️  Found ${option_ref_type}: ${option_ref_value}" >&2
            else
                {
                    echo "ℹ️  Reviewed:"
                    for x in "${_revMarkers[@]}" ; do
                        echo "  •  $x"
                    done
                } >&2
                do_errorExitWithSuggestion "Neither tag:{$option_ref_value} nor branch:${option_ref_value} nor branch:${option_ref_value}-wip could be found in the repository '$option_repo_url'"
            fi
        fi
    fi



    ##############################################
    #

    if [[ -n "$option_ref_type" ]] ; then
        repo_fullDir="${repo_fullDir%/}/${option_ref_type}_${option_ref_value}"
    else
        repo_fullDir="${repo_fullDir%/}/default_branch"
    fi

    [[ -n "$option_ref_type" ]] && repo_friendlyName+=" [$option_ref_type:$option_ref_value]"

    #########################
    #
    # Load:
    # * gitInfo_description
    # * gitInfo_warning
    #
    gitInfo_description=""
    gitInfo_warning=''
    if [[ ! -d "$repo_fullDir" ]] ; then
        gitInfo_description="MISSING"
    elif [[ "$option_is_reload" == "yes" ]] || [[ "$option_is_erase" == "yes" ]] ; then
        do_with_check  rm -rf "$repo_fullDir"
        gitInfo_description="ERASED"
    else
        load_gitInfo
    fi

    if false ; then
    {
        echo "ℹ️  !! ${THIS_EXE} $*"
        echo "ℹ️  !! -----------------------------------------------------"
        echo "ℹ️  !! * repo_friendlyName   = $repo_friendlyName"
        echo "ℹ️  !! * repo_fullDir        = $repo_fullDir"
        echo "ℹ️  !! "
        echo "ℹ️  !! * option_repo_url     = $option_repo_url"
        echo "ℹ️  !! * option_ref_type     = $option_ref_type"
        echo "ℹ️  !! * option_ref_value    = $option_ref_value"
        echo "ℹ️  !! "
        echo "ℹ️  !! * gitInfo_description = $gitInfo_description"
        echo "ℹ️  !! * gitInfo_warning     = $gitInfo_warning"
        echo "ℹ️  !! -----------------------------------------------------"
    } >&2
    fi

    #########################
    #
    # Clear if needed
    #
    if [[ "$option_is_erase" == "yes" ]]; then
        echo -e "$repo_friendlyName: ${COLOUR[VIVID_BLUE_STDERR]:-}ℹ️  $gitInfo_description${COLOUR[OFF_STDERR]:-} " >&2
        return 0
    fi

    if [[ "$gitInfo_warning" == "<INVALID_GIT>" ]] ; then
        giveWarning "$repo_friendlyName: $gitInfo_description -- Removing"
        do_with_check rm -rf "$repo_fullDir"
    elif  [[ "$gitInfo_description" == "<EMPTY>" ]]; then
        echo -e "$repo_friendlyName: ${COLOUR[VIVID_BLUE_STDERR]:-}ℹ️  $gitInfo_description${COLOUR[OFF_STDERR]:-} -- Removing" >&2
        do_with_check rm -rf "$repo_fullDir"
    fi

    #########################
    #
    #
    #

    if [[ ! -d "$repo_fullDir" ]]; then

        mkdir -p "$repo_fullDir"
        cd "$repo_fullDir" || true

        [[ "$option_is_quiet" == 'yes-unless-info' ]] && echo -e "Loading from cloud: ${COLOUR[VIVID_BLUE_STDERR]:-}$repo_friendlyName${COLOUR[OFF_STDERR]:-} into $repo_fullDir" >&2 && option_is_quiet='no'

        #########################
        #
        # Load the repo into $repo_fullDir
        #
        # Update:
        #  * gitInfo_description
        #  * gitInfo_warning
        #

        if [[ "$option_ref_type" == '' ]] ; then
             do_with_check git clone  "$option_repo_url" "$repo_fullDir"
        elif [[ "$option_ref_type" == 'branch' ]] ; then
             do_with_check git clone --branch "$option_ref_value" --depth 1 "$option_repo_url" "$repo_fullDir"
        elif [[ "$option_ref_type" == 'hash' ]] ; then
             do_with_check git clone  "$option_repo_url" "$repo_fullDir"
             do_with_check git -C "$repo_fullDir" checkout -c advice.detachedHead=false  "$option_ref_value"
        elif [[ "$option_ref_type" == 'hash-only' ]] ; then
             url="https://${option_repo_url/:/}/archive/${option_ref_value}.zip"
             do_with_check wget -L -O "/tmp/${option_ref_value}.zip" "$url"
             do_with_check unzip "/tmp/${option_ref_value}.zip" -d "${repo_fullDir}"
        elif [[ "$option_ref_type" == 'tag' ]] ; then
             do_with_check git clone -c advice.detachedHead=false  --branch "$option_ref_value"  --depth 1 "$option_repo_url" "$repo_fullDir"
        else
            giveWarning "Invalid ref type '$option_ref_type' for ref '$option_ref_value'"
            exit 1
        fi

        if [[ "$option_ref_type" != 'hash-only' ]] ; then

            [[ -f "${repo_fullDir%/}/.gitmodules" ]] && do_with_check git submodule update --init --recursive

            if [[ -f "${repo_fullDir%/}/.pre-commit-config.yaml" ]]; then
                if ! command -v pre-commit >/dev/null 2>&1 ; then
                    giveWarning "pre-commit not found in PATH.  Skipping pre-commit install for $repo_friendlyName"
                elif ! pushd "$repo_fullDir" &>/dev/null ; then
                    giveWarning "Unable to enter directory $repo_fullDir to install pre-commit hooks.  Skipping pre-commit install for $repo_friendlyName"
                else
                    do_with_check pre-commit install >&2 # --install-hooks
                    echo "⚡ pre-commit hooks installed for $repo_friendlyName" >&2
                    popd &>/dev/null || true
                fi
            fi
        fi
        load_gitInfo
    fi

    #################################################################################################################################
    # Summarise based on:
    #   * repo_friendlyName
    #   * gitInfo_description
    #   * gitInfo_warning
    #   * repo_fullDir
    #
    local repo_caption="$repo_friendlyName"
    local repo_displayDir="${repo_fullDir}"
    if [[ -n "${HOME:-}" ]] && [[ "$repo_displayDir" == "${HOME%/}/"* ]]; then
        # shellcheck disable=SC2088
        repo_displayDir="~/${repo_displayDir#"${HOME%/}/"}"
    fi
    [[ -n $gitInfo_description ]] &&  repo_caption+=" $gitInfo_description"
    [[ -n "$gitInfo_warning"   ]] &&  gitInfo_warning=" ${COLOUR[VIVID_RED_STDERR]:-}⚠️  $gitInfo_warning${COLOUR[OFF_STDERR]:-}"

    if [[ "$option_is_quiet" != "yes" ]] || [[ -n "$gitInfo_warning" ]] || [[ "$hadWarning" == "yes" ]]; then
        echo -e "Using: ${COLOUR[VIVID_BLUE_STDERR]:-}${repo_caption}${COLOUR[OFF_STDERR]:-}$gitInfo_warning" >&2
        echo -e "       └── $repo_displayDir" >&2
    fi
    echo "$repo_fullDir"
    exit 0
}



##############################################################################################################################################
#
# Utils for this code
#

function getDirs()
{
    local baseDir="$1"
    find "$baseDir" -mindepth 1 -maxdepth 1 -type d | sed --unbuffered "s|^${baseDir%/}/||g"
}


function doListSharedCheckouts()
{

    readarray -t _dirs < <(find "$SHARED_GIT_DIR" -mindepth 4 -maxdepth 4 -type d)

    for _dir in "${_dirs[@]}"; do
        dump_gitInfoOnDir "$_dir"
    done

}

#==============================================================================================
#
# Start Region: Shared between lib-common.inc.bash & single file: git-shared-checkout
#

##############################################
#
# Evaluates git stored in:
#  * repo_fullDir
#
# Loads:
#  * gitInfo_description
#  * gitInfo_warning
#
# Also evaluates and triggers warnings based on:
#  * option_ref_type
#  * option_ref_value
#
gitInfo_description=''
gitInfo_warning=''
function load_gitInfo()
{
    local hash=''
    local branch=''

    local alwaysGiveBranch="${1:-no}"
    gitInfo_description=''
    gitInfo_warning=''

    if [[ ! -d "$repo_fullDir" ]] ; then
        gitInfo_warning="MISSING"
        return
    elif [[ "$option_ref_type" == 'hash-only' ]] ; then
        gitInfo_description="only:#${option_ref_value}"
    elif [[ -n "$(find "$repo_fullDir" -maxdepth 0 -empty)" ]] ; then
        gitInfo_description="<EMPTY>"
    elif ! hash="$(git -C "$repo_fullDir" describe --always --dirty 2>/dev/null)"; then
        gitInfo_warning="<INVALID_GIT>"
    else
        branch="$(git -C "$repo_fullDir" branch --show-current 2>/dev/null || true)"
        gitInfo_description="${branch}@${hash}"
        our_hash="${hash%-dirty}"

        if [[ "$option_ref_type" == "hash" ]] && [[ "${our_hash}" != "$option_ref_value" ]]; then
            gitInfo_warning="Hash is not the expected value: #$option_ref_value"
        elif [[ "$option_ref_type" == "branch" ]] && [[ "$branch" != "$option_ref_value" ]]; then
            gitInfo_warning="Branch is not the expected value: ${option_ref_value:-}"
        elif [[ "$option_ref_type" == "hash" ]] ; then
            if [[ "${hash}" == *-dirty ]]; then
                gitInfo_description="🔓  "
            else
                gitInfo_description="🔒  "
            fi
        elif [[ "$option_ref_type" == "branch" ]] ; then
            if [[ "$alwaysGiveBranch" == "yes" ]] ; then
                gitInfo_description="🔓  ${gitInfo_description}"
            else
                gitInfo_description="🔓  @${hash}"
            fi
        elif [[ "$option_ref_type" == "tag" ]] ; then
            tag_hash="$(git -C "$repo_fullDir" rev-list -n 1 "refs/tags/${option_ref_value}" 2>/dev/null || true)"
            if [[ -z "$tag_hash" ]] ; then
                gitInfo_warning="Unable to identify tag:${option_ref_value}"
            elif [[ "${tag_hash}" != "${our_hash}"* ]]; then
                gitInfo_warning="tag:${option_ref_value}=#${tag_hash:0:7}"
            else
                gitInfo_description+="🔓  "
            fi
        elif [[ -z "$option_ref_type" ]] ; then
            gitInfo_description="🔓  ${gitInfo_description}"
        else
            gitInfo_description+="🔓  "
        fi
        if [[ "$hash" == *-dirty ]] ; then
            [[ -n "$gitInfo_warning" ]] && gitInfo_warning+=" & "
            gitInfo_warning+="There are local changes"
        fi
    fi
}

function dump_gitInfoOnDir()
{
    local _dir="$1"

    repo_fullDir="$_dir"

    y="${repo_fullDir#"$SHARED_GIT_DIR/"}"

    repo_friendlyName="${y%/*}"
    repo_friendlyName="${repo_friendlyName/\//:}"
    _dispDir="${SHARED_GIT_DIR_DISPLAY%/}/$y"
    _checkoutDirPart="${y##*/}"
    _repoDirPart="${y%/*}"

    if [[ "$_checkoutDirPart" == "default_branch" ]]; then
        option_ref_type=""
        option_ref_value=""
        _checkoutKindValue=""
    else
        option_ref_type="${_checkoutDirPart%%_*}"
        option_ref_value="${_checkoutDirPart#*_}"
        _checkoutKindValue="$option_ref_type:$option_ref_value"
    fi

    # Load:
    # * gitInfo_description
    # * gitInfo_warning
    load_gitInfo 'yes'

    ##########
    # Summarise

    local repo_caption="$repo_friendlyName"
    [[ -n $gitInfo_description ]] &&  repo_caption+=" $gitInfo_description"
    local _dirAsPrinted="$_dispDir"

    [[ -z "$gitInfo_warning"   ]] || gitInfo_warning=" ${COLOUR[VIVID_RED_STDERR]:-}⚠️  $gitInfo_warning${COLOUR[OFF_STDERR]:-}"
    _checkoutDirPart="${y##*/}"
    _repoDirPart="${y%/*}"
    echo -en  " •  ${SHARED_GIT_DIR_DISPLAY%/}/${COLOUR[VIVID_BLUE_STDOUT]:-}${_repoDirPart}${COLOUR[OFF_STDOUT]:-}/${_checkoutDirPart} "

    _maxLen=80
    _a="${#_repoDirPart}"
    _b="${#_checkoutDirPart}"

    printf "%-*s" "$((_maxLen - _a - _b - 3))" ""
    echo -e "${COLOUR[VIVID_BLUE_STDOUT]:-}${gitInfo_description}${COLOUR[OFF_STDOUT]:-}$gitInfo_warning"
}

function displayPath()
{
    local fname_in="$1"

    shift 1 || true

    local trailingFile
    local pathToReview

    if [[ "${1:-}" == "--link-src" ]] ; then
        shift 1 || true
        local dir="${fname_in%/*}"

        pathToReview="${dir:-"${PWD}"}"
        trailingFile="${fname_in##*/}"
    else
        pathToReview="$fname_in"
        trailingFile=''
    fi

    local max_back=4
    if [[ "${1:-}" == "--max-back="* ]] ; then
        max_back="${1#--max-back=}"
        shift 1 || true
    fi
    skip_relative_if_contains="$(printf -v spaces "%*s" "$max_back" "" && echo "${spaces// /../}")"
    skip_relative_if_contains="${skip_relative_if_contains%/}"

    local orig
    local relPath
    local result

    orig="$(realpath "${pathToReview}")"
    result="${orig/#$HOME/\~}"
    relPath="$(realpath --relative-to="${ORIG_PWD%/}/" "${orig}")"
    [[ "${1:-}" == "--run-path" ]] && [[ "$relPath" != *"/"* ]] && [[ "$relPath" != "./"* ]] && [[ "$relPath" != "." ]] && relPath="./${relPath}"
    [[ "$relPath" != *"${skip_relative_if_contains}"* ]] && [[ "${#result}" -gt  "${#relPath}" ]] && result="$relPath"
        skip_relative_if_contains="${skip_relative_if_contains%/}"

    if [[ "${1:-}" == "--run-path" ]] ; then
        # Is this exe available in PATH ?

        if [[ -n "$trailingFile" ]] ; then
            local exe_dir="${orig%/}"
            local exe_name="$trailingFile"
        else
            local exe_dir="${orig%/*}"
            local exe_name="${fname_in##*/}"
        fi

        IFS=: read -r -d '' -a path_array < <(printf '%s:\0' "$PATH")
        # Loop through the array elements
        for pathDir in "${path_array[@]}"; do
            [[ -n "$pathDir" ]] || pathDir="$PWD"
            if [[ "$pathDir" == "$exe_dir" ]] ; then
                quoteIfNeeded "$exe_name"
                return 0  #< This can't be beaten for shortness - No path!
            fi
        done
    fi
    local fname_out
    if [[ -z "$result" ]] ; then
        fname_out="$orig"
    elif [[ -z "$trailingFile" ]] ; then
        fname_out="$result"
    else
        fname_out="${result%/}/$trailingFile"
    fi

    if [[ "${1:-}" == "--run-path" ]] ; then
        fname_out="$(quoteIfNeeded "$fname_out")"
    fi

    echo -n "$fname_out"
}



function relativeToOrigPwd()
{
  realpath --relative-to="${ORIG_PWD%/}/" "${1}"
}


function _quoteIfNeeded()
{
    local permitDoubleQuoting="${1}"
    shift 1

    local value
    local result=''

    for value in "$@" ; do
        [[ -n "$result" ]] && echo -n " "

        issues=''
        result="$value"

        doubleQuotable="${permitDoubleQuoting:-yes}"
        [[ "$value" == ''    ]] && issues+='[empty]'
        [[ "$value" == *"'"* ]] && issues+='[singleQuotes]'
        [[ "$value" == *'"'* ]] && issues+='[doubleQuotes]' && doubleQuotable='no'
        [[ "$value" == *" "* ]] && issues+='[spaces]'
        [[ "$value" == *'`'* ]] && issues+='[backticks]'    && doubleQuotable='no'
        [[ "$value" == *'$'* ]] && issues+='[dollarSigns]'  && doubleQuotable='no'
        [[ "$value" == *'|'* ]] && issues+='[pipes]'
        [[ "$value" == *'&'* ]] && issues+='[ampersands]'
        [[ "$value" == *'('* ]] && issues+='[openParens]'
        [[ "$value" == *')'* ]] && issues+='[closeParens]'
        [[ "$value" == *'{'* ]] && issues+='[openBraces]'
        [[ "$value" == *'}'* ]] && issues+='[closeBraces]'
        [[ "$value" == *'['* ]] && issues+='[openBrackets]'
        [[ "$value" == *']'* ]] && issues+='[closeBrackets]'
        [[ "$value" == *'<'* ]] && issues+='[lessThan]'
        [[ "$value" == *'>'* ]] && issues+='[greaterThan]'
        [[ "$value" == *';'* ]] && issues+='[semicolons]'
        # shellcheck disable=SC1003
        [[ "$value" == *'\'* ]] && issues+='[backslashes]'


        if [[ -n "$issues" ]] ; then
            if [[ "$doubleQuotable" == 'yes' ]] ; then
                result="\"${value}\""
            elif [[ "$issues" != *'[singleQuotes]'* ]] ; then
                result="'${value}'"
            else
                result="$(printf "%q" "$value")"
            fi
            #|Logging| printf "   Value \`%s\` will be quote protected: %s\n" "$value" "$result" >&2
        fi

        echo -n "$result"
    done
    return 0
}

function quoteIfNeeded()
{
    _quoteIfNeeded "yes" "$@"
}

##################################################
#
# Colours
#
declare -A COLOUR=()
declare -A COLOUR_CODES=(
        [RED]='\033[0;31m'
        [GREEN]='\033[0;32m'
        [YELLOW]='\033[0;33m'
        [BLUE]='\033[0;34m'

        [VIVID_RED]='\033[1;31m'
        [VIVID_GREEN]='\033[1;32m'
        [VIVID_YELLOW]='\033[1;33m'
        [VIVID_BLUE]="\033[1;34m"

        [OFF]='\033[0m'
)

UKKO_COLOURS_CHOSEN=''

function colours_setUsed()
{
    local kind="${1:-stdout}"  # stdout,stderr
    UKKO_COLOURS_USED_SUFFIX="_${kind^^}"
    for colourName in "${!COLOUR_CODES[@]}"; do
        contents="${COLOUR[${colourName}${UKKO_COLOURS_USED_SUFFIX}]:-}"
        if [[ -z "$contents" ]] ; then
            unset "COLOUR[${colourName}_USED]"
        else
            COLOUR["${colourName}_USED"]="$contents"
        fi
    done
}
function colours_load()
{
    local arg="${1:-auto}"  # yes|no|auto

    UKKO_COLOURS_CHOSEN="--colours=$arg"

    [[ -t 1 ]] || UKKO_COLOURS_CHOSEN+=", stdout redirected"
    [[ -t 2 ]] || UKKO_COLOURS_CHOSEN+=", stderr redirected"

    # |x| echo "colours_load($arg): $UKKO_COLOURS_CHOSEN" >&2
    local kind
    local colourName
    local colourCode

    COLOUR=()

    for kind in "_STDOUT" "_STDERR" "_FORCED"; do

        _colour=yes
        if [[ "$arg" == 'no' ]] ; then
            [[ "$kind" == "_FORCED" ]] || _colour=no
        elif [[ "$arg" == 'auto' ]] ; then
            [[ "$kind" == "_STDOUT" ]] && [[ ! -t 1 ]] && _colour=no
            [[ "$kind" == "_STDERR" ]] && [[ ! -t 2 ]] && _colour=no
        fi

        if [[ "$_colour" == 'yes' ]]; then

            for colourName in "${!COLOUR_CODES[@]}"; do
                local colourCode="${COLOUR_CODES[$colourName]}"

                local codeName="${colourName}"
                [[ -n "$kind" ]] && codeName+="$kind"

                COLOUR["${codeName}"]="$colourCode"
            done
        fi
    done

    colours_setUsed "stdout"
}

colours_load "yes"

#
##################################################################################

overallBashResult=0
function doRun()
{
    local silent_if_ok=no

    if [[ "${1:-}" == "--silent-if-ok" ]] ; then
        silent_if_ok=yes
        shift 1 || true
    fi
    local expected_result=0
    if [[ "${1:-}" == "--expect-exit-code="* ]] ; then
        expected_result="${1#--expect-exit-code=}"
        shift 1 || true
    fi

    local result=0

    local tmpfile ; tmpfile="$(mktemp "/tmp/doRun.XXXXXX")"


    "$@" &> "$tmpfile" || result=$?

    local exitCodeNote=''

    [[ "$result" -ne 0 ]] && exitCodeNote="[Exit code: $result]"

    if [[ "$result" == "$expected_result" ]]; then
        [[ "$silent_if_ok" == "yes" ]] && return 0
        echo "      ✓ Ran${exitCodeNote}: $*"
    else
        echo "      ✗ Ran${exitCodeNote}: $*"UK
        echo "        ❌ Responded with: $result"
        # shellcheck disable=SC2034
        overallBashResult="$result"
    fi
    [[ -s "$tmpfile" ]] && withLeftBox "             " < "$tmpfile"

    rm -f "$tmpfile"
    return $result
}

function withPrefix()
{
    local prefix="$1"
    sed --unbuffered "s/^/${prefix}/" || return 0
}

function withLeftBox()
{
    local prefix="${1:-}"
    echo       "${prefix}╭───────────────────────────────────────────────────────────────────────"
    withPrefix "${prefix}│ "
    echo       "${prefix}╰───────────────────────────────────────────────────────────────────────"
}

function doRun-groupedOutput()
{
    local result
    echo                   "╭───────────────────────────────────────────────────────────────────────"
    "$@" 2>&1 | withPrefix "│ "
    result="${PIPESTATUS[0]}"
    echo                   "╰───────────────────────────────────────────────────────────────────────"
    return "$result"
}

function doWithSuccessMsg()
{
    local success_msg="$1"

    shift 1 || true

    doRun --silent-if-ok "$@" || return $?

    echo "$success_msg"
}

function sudoIfNeeded() {
    export DEBIAN_FRONTEND=noninteractive
    if [[ "$(id -u)" -ne 0 ]] ; then
        sudo sudo ORIG_PWD="${ORIG_PWD:-}" "$@"
    else
        "$@"
    fi
}


function do_remove_link()
{
    local link="$1"
    local optional_unless_target="${2:-}"

    if [[ -L "$link" ]] ; then
        if [[ -n "${optional_unless_target}" ]] && [[ "$(readlink -f "$link")" == "$(readlink -f "$optional_unless_target")" ]] ; then
            echo "    • Keeping link : $(displayPath "$link" --link-src) → $(displayPath "$optional_unless_target")"
        else
            doWithSuccessMsg "    • Unlinked existing: $(displayPath "$link" --link-src)"  unlink "$link"  || return $?
        fi
    elif [[ -e "$link" ]] ; then
        doWithSuccessMsg "    • Removed existing file/directory: $(displayPath "$link" --link-src)"  rm -rf "$link" || return $?
    fi
}

function do_ensure_link()
{
    local link="$1"
    local target="$2"

    if [[ "${AM_CLEANING:-}" == 'yes' ]] ; then
        do_remove_link "$link" || return $?
    elif [[ -L "$link" ]] && [[ "$(readlink -f "$link")" == "$(readlink -f "$target")" ]] ; then
        printf "    • Link confirmed: %-24s → %s\n" "$(displayPath "$link" --link-src)" "$(displayPath "$target")"
    else
        do_remove_link "$link" || return $?
        target_parent="$(dirname "$target")"
        [[ -d "$target_parent" ]] || doWithSuccessMsg "    • Created parent : $(displayPath "$target_parent")"  mkdir -p "$target_parent" || return $?
        doWithSuccessMsg "    • Created link: $(displayPath "$link" --link-src) → $(displayPath "$target")"  ln -s "$target" "$link" || return $?
    fi

    return 0
}

function do_ensure_file_set()
{
    local dest_fname="$1"
    local src_fname="$2"
    local gave_success_msg="no"

    if [[ -L "$dest_fname" ]] || [[ ! -f "$dest_fname" ]] || ! cmp --silent "$dest_fname" "$src_fname" ; then
        do_remove_link "$dest_fname"  || return $?
        doWithSuccessMsg "    • Updated file: $(displayPath "$dest_fname")"  cp "$src_fname" "$dest_fname" || return $?
        gave_success_msg='yes'
    fi


    local src_attr ; src_attr=$(stat --printf="%a" "$src_fname")
    local dst_attr ; dst_attr=$(stat --printf="%a" "$dest_fname")
    if [[ "$src_attr" != "$dst_attr" ]] ; then
        doWithSuccessMsg "    • Updated permissions for $(displayPath "$dest_fname") : $dst_attr → $src_attr"  chmod "$src_attr" "$dest_fname" || return $?
        gave_success_msg='yes'
    fi


    [[ "$gave_success_msg" == 'yes' ]] || echo "    • File confirmed: $(displayPath "$dest_fname")"
    return 0
}

#
# End Region: Shared bewteen lib-common.inc.bash & single file: git-shared-checkout
#
#==============================================================================================

THIS_EXE="$(readlink -m "${BASH_SOURCE[0]}")"
ORIG_PWD="$(pwd)"
CMD_AS_DISPLAY="$(displayPath "$0" --link-src --run-path)"

#==============================================================================================
#
# This is a standard template for bash scripts that uses:
#  * APP_VERSION     | Optional but recommended
#  * APP_DESCRIPTION | Optional
#
#  * app_help        | Optional but recommended
#  * app_load_param  | Optional but recommended
#  * app_run         | Required
#
# Example usage:
#
# ╭─────────────────────────────────────────────────────────────────────────────────────
# │ #!/usr/bin/env bash
# │  set -eu
# │  APP_VERSION="1.0.0"
# │  APP_DESCRIPTION="This app says 'hello'"
# │
# │ function app_help()
# │ {
# │     echo -e "Usage: ${COLOUR[VIVID_BLUE_USED]:-}$CMD_AS_DISPLAY [--person=<name>]${COLOUR[OFF_USED]:-}"
# │     echo -e "       --person=<name>    Specify the name to greet (default: 'fred')"
# │ }
# │
# │ function app_load_param_defaults()
# │ {
# │     option_person='fred'
# │ }
# │
# │ function app_load_param_option_name_value()
# │ {
# │     [[ "$1" == '--person' ]] && option_person="$2" && return 0
# │
# │     return 1
# │ }
# │ function app_run()
# │ {
# │     echo "Hello: $option_person"
# │     giveWarning "This is a warning message - these are sent to stderr"
# │     echo "This is some more output"
# │     echo -e "Hidden coding help is available with: ${COLOUR[VIVID_BLUE_STDOUT]:-}$CMD_AS_DISPLAY --code-help${COLOUR[OFF_STDOUT]:-}"
# │ }
# │ # shellcheck disable=SC1091
# │ source "$(git-shared-checkout git@github.com:smc-collaborate/ukko_bashlibs --ref="${UKKO_BASHLIBS_REF:-}")/lib-common.inc.bash"
# ╰─────────────────────────────────────────────────────────────────────────────────────
#
# It makes available:
#
#    $EXE_NAME
#    $THIS_EXE
#    do_errorExitWithSuggestion  "<optional error message>"
#    do_with_check <command...>  - Run a command and exit with an error message if it fails
#    giveWarning "<warning message>" - Give a warning message that will be shown at the end of processing (if any)
#

function padRight()
{
    local width="$1"
    local text="$2"

    [[ "$width" -lt 0 ]] && width=0
    printf "%-${width}s" "$text"
}

function giveCodeHelp()
{
    # this is dumped with the hidden option '--code-help'

    echo " This is a standard template for bash scripts that uses:"
    echo "  * APP_VERSION                                   | Optional but recommended"
    echo "  * APP_DESCRIPTION                               | Optional"
    echo ""
    echo "  * app_help()                                    | Optional but recommended"
    echo "  * app_load_param_defaults()                     | Optional but recommended"
    echo "  * app_load_param_option_name_value(name,value)  | Optional but recommended"
    echo "  * app_load_param_direct_value(value)            | Optional"
    echo "  * app_run()                                     | Required"
    echo ""
    echo " It makes available:"
    echo ""
    echo  "    Name                 │ Description                                     │ Value"
    echo  "    ─────────────────────┼─────────────────────────────────────────────────┼────────────────────────"
    echo "    \$EXE_NAME            │ The name of the executable (e.g. 'myscript.sh') │ ${EXE_NAME:-❓  Not defined}"
    echo "    \$THIS_EXE            │ The full path to the executable                 │ ${THIS_EXE:-❓  Not defined}"
    echo "    \$EXE_DIR             │ The directory of the executable                 │ ${EXE_DIR:-❓  Not defined}"
    echo "    \$THIS_EXE_AS_DISPLAY │ The display path of the executable              │ ${THIS_EXE_AS_DISPLAY:-❓  Not defined}"
    echo "    \$CMD_AS_DISPLAY      │ The executable in a form that can be run        │ ${CMD_AS_DISPLAY:-❓  Not defined}"
    echo ""
    echo "    do_exitWithHelp  '<optional error message>'"
    echo "    do_errorExitWithSuggestion  '<error message>'"
    echo "    do_with_check <command...>  - Run a command and exit with an error message if it fails"
    echo "    giveWarning '<warning message>' - Give a warning message that will be shown at the end of processing (if any)"
    echo "   "

    colours_show
}

# shellcheck disable=SC2317
function do_errorExitWithSuggestion()
{
    local fatal_error_message="${1:-}"
    {
        echo -e "${COLOUR[VIVID_RED_STDERR]:-}❌  $fatal_error_message${COLOUR[OFF_STDERR]:-}"
        echo -e "Suggest: ${COLOUR[VIVID_BLUE_STDOUT]:-}$CMD_AS_DISPLAY --help${COLOUR[OFF_STDOUT]:-}"
    } >&2
    exit 1
}

function do_errorExitWithSuggestion()
{
    local fatal_error_message="${1:-}"
    {
        echo -e "${COLOUR[VIVID_RED_STDERR]:-}❌  $fatal_error_message${COLOUR[OFF_STDERR]:-}"
        echo -e "Suggest: ${COLOUR[VIVID_BLUE_STDOUT]:-}$CMD_AS_DISPLAY --help${COLOUR[OFF_STDOUT]:-}"
    } >&2
    exit 1
}

function do_exitWithHelp()
{
    local fatal_error_message="${1:-}"

    [[ -n "$fatal_error_message" ]] && echo -e "${COLOUR[VIVID_RED_STDERR]:-}❌  $fatal_error_message${COLOUR[OFF_STDERR]:-}" >&2
    {

        colours_setUsed 'STDERR'

        [[ -n "${APP_DESCRIPTION:-}" ]] && echo -e "$CMD_AS_DISPLAY: $APP_DESCRIPTION"
        if declare -F app_help >/dev/null 2>&1 ; then
            app_help
            echo ""
            echo -e "Additional functions:"
        else
            echo -e "Usage: ${COLOUR[VIVID_BLUE_USED]:-}$CMD_AS_DISPLAY <parameters>${COLOUR[OFF_USED]:-}"
            echo -e ""
            echo -e "Parameters:"
        fi
        echo -e "     --help     : Give this help message"
        [[ -n "${APP_VERSION:-}" ]] && echo -e "     --version  : Give version : ${COLOUR[VIVID_BLUE_USED]:-}$APP_VERSION${COLOUR[OFF_USED]:-}"

        _installDirShow="$(displayPath "$INSTALL_DIR")"
        [[ ":$PATH:" == *":${INSTALL_DIR}:"* ]] || _installDirShow+="${COLOUR[VIVID_RED_USED]:-}  ⚠️  This should be added to \$PATH${COLOUR[OFF_USED]:-}"
        if [[ "${APP_SELF_INSTALL:-}" == "yes" ]] ; then
            if [[ "$INSTALLATION_NOTE" == "OK" ]] ; then
                echo -e "     --uninstall: Uninstalls from $_installDirShow"
            else
                echo -e "     --install  : Installs to $_installDirShow "
            fi
        fi
        echo -e "     --colours=no|yes|auto  (Default 'auto')"
    } >&2

    if [[ -n "$fatal_error_message" ]]; then
        exit 1
    else
        exit 0
    fi
}


function app_load_param_validate_from_list()
{
    local name="$1"
    local value="$2"

    shift 2 || true
    #echo "ℹ️  Validating value for $name$value against expected values: [$(asCsvList "$@")]"

    for arg in "$@"; do
        [[ "$arg" == "$value" ]] && return 0
    done
    do_errorExitWithSuggestion "Invalid value for ${name}<value>.  <value> is ${value@Q}, but expected one of [$(asCsvList "$@")]"
}

function load_params()
{
    local am_processing_options='yes'
    function _app_get_param_defaults()
    {
        declare -F app_load_param_defaults  &> /dev/null  || return 0 ; app_load_param_defaults
    }
    function _app_get_param_option_name_value()
    {
        declare -F app_load_param_option_name_value  &> /dev/null  && app_load_param_option_name_value "$1" "${2:-}"
    }


    function _app_get_param_direct_value()
    {
        declare -F app_load_param_direct_value  &> /dev/null  && app_load_param_direct_value "$1"
    }


    _app_get_param_defaults
    local giveCodeHelp='no'
    local giveStdHelp='no'
    for arg in "$@"; do
        [[ -z "$arg" ]] && continue
        if [[ "$am_processing_options" == "yes" ]] && [[ "$arg" == '-'* ]]; then
            if [[ "$arg" == '--' ]] ; then
                am_processing_options='no'
            elif [[ "$arg" == '--version' ]] && [[ -n "${APP_VERSION:-}" ]]; then
                echo "$(basename "$THIS_EXE") $APP_VERSION"
                exit 0
            elif [[ "$arg" == '--help' ]]; then
                giveStdHelp='yes'
            elif [[ "$arg" == '--colours=no' ]] || [[ "$arg" == '--colours=yes' ]] || [[ "$arg" == '--colours=auto' ]]; then
                colours_load "${arg#--colours=}"
            elif [[ "${APP_SELF_INSTALL:-}" == "yes" ]] && [[ "$INSTALLATION_NOTE" == "OK" ]] && [[ "$arg" == "--uninstall" ]] ; then
                (sleep 0.5 && rm -f "$THIS_EXE" && echo "Removed $THIS_EXE") &
                exit 0
            elif [[ "${APP_SELF_INSTALL:-}" == "yes" ]] && [[ "$arg" == "--install" ]] ; then # Always permit 'install' even if the app is already installed, as this can be used to fix an installation that is not working (e.g. due to missing copy or missing PATH entry)
                do_install_directly "      "
                exit 0
            elif [[ "$arg" == '--code-help' ]] ; then
                giveCodeHelp='yes'
            elif [[ "$arg" == "--"*"="* ]] ; then
                _app_get_param_option_name_value "${arg%%=*}=" "${arg#*=}" || do_errorExitWithSuggestion "Unknown named option ${arg@Q}"
            else
                _app_get_param_option_name_value "${arg}"                  || do_errorExitWithSuggestion "Unknown option ${arg@Q}"
            fi
        else
            _app_get_param_direct_value "$arg" || do_errorExitWithSuggestion "Unknown direct argument ${arg@Q}"
        fi
    done

    if [[ "$giveCodeHelp" == "yes" ]]; then
        giveCodeHelp
        exit 0
    elif [[ "$giveStdHelp" == "yes" ]]; then
        do_exitWithHelp ""
    fi

}

function do_with_check()
{
    local caption="$*"

    local caption_decorated="$*"
    if [[ "$1" == '--caption='* ]]; then
        caption="${1#--caption=}"
        shift
    else
        caption_decorated="${COLOUR[VIVID_BLUE_STDERR]:-}$caption${COLOUR[OFF_STDERR]:-}"
    fi
    local status=0
    local suffix=''

    echo -e "Running : ${caption_decorated}" >&2
    "$@" || status=$?
    if [[ "$status" == 0 ]] ; then
        true #echo -e "          -- OK" >&2
    else
        [[ "$status" == 1 ]] || suffix=" with status $status"
        echo -e "Ran    :${COLOUR[VIVID_RED_STDERR]:-}$caption${COLOUR[OFF_STDERR]:-} -- Failed$suffix" >&2
        [[ "$caption" == "$*" ]] || echo -e "Command: ${COLOUR[VIVID_BLUE_STDERR]:-}$*${COLOUR[OFF_STDERR]:-}" >&2
        exit 1
    fi
}


function do_install_directly()
{
    local prefix="${1:-}"
    if [[ "$INSTALLATION_NOTE" == "OK" ]]; then
        echo -e "${prefix}${COLOUR[VIVID_GREEN_STDOUT]:-}✅ $app_name_and_version is already successfully installed to  ${INSTALL_DIR@Q}${COLOUR[OFF_STDOUT]:-}"
        return 0
    fi

    if [[ "$INSTALLATION_NOTE" == *"[NotCopied]"* ]] ; then
        if ! do_ensure_file_set  "$INSTALL_DIR_WITH_EXE" "$THIS_EXE" ; then
            echo -e "${prefix}${COLOUR[VIVID_RED_STDERR]:-}❌  Failed to copy $THIS_EXE to $INSTALL_DIR_WITH_EXE${COLOUR[OFF_STDERR]:-}"
            return 1
        fi
    fi

    if [[ "$INSTALLATION_NOTE" == *"[DirNotInPath]"* ]] ; then
        echo -e "${prefix}${COLOUR[VIVID_RED_STDERR]:-}⚠️  $app_name_and_version installed to ${INSTALL_DIR@Q} but it is NOT in PATH. Please add ${INSTALL_DIR@Q} to your PATH environment variable.${COLOUR[OFF_STDERR]:-}" >&2
        return 1
    fi
     echo -e "${prefix}✅  ${COLOUR[VIVID_BLUE_STDOUT]:-}$app_name_and_version${COLOUR[OFF_STDOUT]:-} installed successfully to ${INSTALL_DIR@Q} and is available in PATH"
}


hadWarning='no'
function giveWarning()
{
    # shellcheck disable=SC2034
    hadWarning='yes'
    [[ -n "$*" ]] && echo -e "${COLOUR[VIVID_RED_STDERR]:-}⚠️  $*${COLOUR[OFF_STDERR]:-}" >&2
}


EXE_NAME="$(basename "$THIS_EXE")"
app_name_and_version="${EXE_NAME}"
[[ "${APP_VERSION:-}" ]] && app_name_and_version+=" ($APP_VERSION)"

INSTALL_DIR="${HOME%/}/.local/bin" ; [[ "$EUID" -eq 0 ]] && INSTALL_DIR="/usr/local/bin"
INSTALL_DIR_WITH_EXE="${INSTALL_DIR%/}/$EXE_NAME"
INSTALLATION_NOTE=''
if [[ "$INSTALL_DIR_WITH_EXE" != "$THIS_EXE" ]]; then
    INSTALLATION_NOTE+='[NotCopied]'
elif ! [[ ":$PATH:" == *":$INSTALL_DIR:"* ]]; then
    INSTALLATION_NOTE+='[DirNotInPath]'
else
    INSTALLATION_NOTE+='OK'
fi


function colours_show()
{

        echo '╭─────────────────────────────────────────────────────────'
        {
            echo "Colour support is available in the script:"
            echo "  eg: echo -e \"This is \${COLOUR[VIVID_BLUE_STDOUT]:-}blue\${COLOUR[OFF_STDOUT]:-}\""
            echo "      echo -e \"This is \${COLOUR[VIVID_BLUE_STDERR]:-}blue\${COLOUR[OFF_STDERR]:-}\" >&2"
            echo ""
            echo "Redirection of stdout and stderr will automatically disable colours for that stream (e.g. \"echo test > out.txt\" or \"echo test 2> err.txt\")"
            echo "You can also force enable or disable colours with the --colours option (e.g. \"--colours=yes\" or \"--colours=no\")"
            echo ""

            if [[ "${#COLOUR[@]}" == 0 ]] ; then
                echo "There are no colours available in the current configuration:  ($UKKO_COLOURS_CHOSEN)"
            else

                echo "The colours available in the current configuration ($UKKO_COLOURS_CHOSEN) are:"

                for colourName in "${!COLOUR[@]}"; do
                    if [[ "$colourName" != "OFF"* ]]; then
                        if [[ "$colourName" == *"_STDOUT" ]]; then
                            offCode="OFF_STDOUT"
                        elif [[ "$colourName" == *"_STDERR" ]]; then
                            offCode="OFF_STDERR"
                        elif [[ "$colourName" == *"_FORCED" ]]; then
                            offCode="OFF_FORCED"
                        else
                            offCode="OFF"
                        fi

                        printf ' • echo -e %-34s%-22s%-28s → ' "\"\${COLOUR[$colourName]:-}\"" "${colourName@Q}" "\"\${COLOUR[$offCode]:-}\""
                        echo -e "${COLOUR[$colourName]}$colourName${COLOUR[$offCode]:-}"

                    fi
                done
            fi
            echo ""
            list=''
            for colourName in "${!COLOUR_CODES[@]}"; do
                if [[ "$colourName" != "OFF" ]] ; then
                [[ -z "$list" ]] || list+=","
                list+=" $colourName"
                fi
            done
            echo "The base colours are: ${list}"
            echo ""
        } | sed --unbuffered 's/^/│/g'
        echo '╰─────────────────────────────────────────────────────────'
}



#################
#


# |x| echo "ℹ️  !! RUNNING:  $0 $*" >&2
load_params "$@"

app_run "$@"
