#!/usr/bin/env bash
set -eu
############################################################
# This is basically equivalent to:
#
# docker run -it -v "$(pwd)":/app "ubuntu:24.04" bash
#
#    root@ab92bb7bcd54:/# cd app
#    root@ab92bb7bcd54:/app# do-full-install-from-blank.sh
#
############################################################

APP_VERSION="0.0.1"
APP_DESCRIPTION="Runs a command on a docker image with some supportive extras (e.g. copying ssh keys, mounting the app directory, etc.)"

function app_help()
{
    echo -e "Usage : ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} <docker-image> [options] -- [cmd to run] [parameters for cmd..]${COLOUR[OFF_USED]:-}"
    echo ""
    echo "Options:  <docker-image>     : Docker image to use for testing (e.g. 'ubuntu:22.04')"
    echo ""
    echo "          --exit=yes         : Always exit after running the command  **DEFAULT**"
    echo "          --exit=no          : Don't exit automatically after running the command"
    echo "          --exit=on-success  : Stay in docker if the command fails - otherwise exit"
    echo ""
    echo "          --keys-dir=<dir>   : The directory containing SSH keys that the container may use"
    echo "                               (Default: ~/.ssh/)"
    echo "          --workspace=<dir>  : The directory to be mapped to '/workspace' inside the container"
    echo "                               (Default: $(displayPath "$ORIG_PWD"))"
    echo "          --apt-get=yes      : Perform \`apt-get update\` and steps"
    echo ""
    echo "          --dry-run          : Does a dry-run without actually executing the command (useful for experiments)"
    echo ""
    echo -e "Example  : ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} ubuntu:22.04 --exit=no  -- echo 'Hello, World!'${COLOUR[OFF_USED]:-}"

    readarray -t _builders < <(find "$ORIG_PWD" -mindepth 1 -maxdepth 1 -type f -executable -name '*do-build*')

    for cmd in "${_builders[@]}" ; do
        echo -e "           ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} ubuntu:24.04 --apt-get=yes -- ./${cmd##*/} --with-tests${COLOUR[OFF_USED]:-}"
    done
}

function app_load_param_defaults()
{
    option_docker_image=''
    option_exit='on-success'
    option_workspace="$ORIG_PWD"
    option_keys_dir='' ;   [[ -n "${HOME:-}" ]] && option_keys_dir="${HOME%/}/.ssh/"
    option_dry_run=''
    option_apt_get='no'
    option_cmd_to_run=()
}

function app_load_param_direct_value()
{
    [[ -z "${option_docker_image:-}" ]] && option_docker_image="$1" && return 0

    option_cmd_to_run+=("$1")
    return 0
}

function app_load_param_option_name_value()
{
    [[ "$1" == '--docker-image=' ]] && option_docker_image="$2" && return 0
    [[ "$1" == '--workspace='    ]] && option_workspace="$2"    && return 0
    [[ "$1" == '--keys-dir='     ]] && option_keys_dir="$2"     && return 0
    [[ "$1" == '--exit='         ]] && option_exit="$2"         && app_load_param_validate_from_list "$1" "$2" yes no on-success && return 0
    [[ "$1" == '--dry-run'       ]] && option_dry_run='yes'     && return 0
    [[ "$1" == '--apt-get='      ]] && option_apt_get="$2"      && app_load_param_validate_from_list "$1" "$2" yes no && return 0
    return 1
}

function app_run()
{
    [[ -n "${option_docker_image:-}" ]] || do_errorExitWithSuggestion "Docker image not specified"

    #[[ "$option_dry_run" != 'yes']] && ! command -v docker &> /dev/null && do_errorExitWithSuggestion "Docker is not installed or not in PATH. Please install Docker to use this app."

    echo "Running within docker image with parameters [$(quoteIfNeeded "$@")]"

    option_workspace="$(realpath -m "${option_workspace}")"

    docker_params=(docker run -it)

    ######
    #
    tmpdir_for_startup_script="$(mktemp -d '/tmp/runWithinImage_XXXX')"
    cp -a "${THIS_DIR%/}/_internalUse/do-run-in-docker_startup.sh" "${tmpdir_for_startup_script}/_startup.sh"

    if [[ "${option_apt_get}" == "yes" ]] ; then
       {
            echo "#!/usr/bin/env bash"
            echo "set -eu"
            echo "apt-get update"
            echo "apt-get install -y git"
            echo "git config --global --add safe.directory /workspace#"
            echo "cat /etc/os-release"
        } | create_executable_run_script "pre-0001-apt-get-update-and-install-git.sh"
    fi



    docker_params+=("-v" "${tmpdir_for_startup_script%/}/:/startup")
    if [[ -n "${option_keys_dir:-}" ]]; then
        mkdir -p "${tmpdir_for_startup_script}/ssh_keys"
        cp -a "${option_keys_dir%/}/"* "${tmpdir_for_startup_script}/ssh_keys/"
    fi
    #
    ######
    [[ -n "${option_workspace:-}"  ]] && docker_params+=("-v" "${option_workspace%/}/:/workspace")
    docker_params+=("${option_docker_image}")
    docker_params+=("bash" "/startup/_startup.sh" "--exit=${option_exit}")

    [[ "${#option_cmd_to_run[@]}" -gt 0 ]] && docker_params+=("run:" "${option_cmd_to_run[@]}")

    echo "             -> $(quoteIfNeeded "${docker_params[@]}")"

    [[ -n "${option_dry_run:-}" ]] && echo "Dry-run mode enabled, not executing the docker command." && exit 0

    local result=0
    "${docker_params[@]}" || result="$?"

    echo "ℹ️  Returned from docker with exit code: $result" >&2

    rm -rf "${tmpdir_for_startup_script}"

    exit "$result"
}

function create_executable_run_script()
{
    local script_path="${tmpdir_for_startup_script%/}/${1}"

    cat > "$script_path"

    chmod +x "$script_path"
}
source "$(dirname "$(realpath -m "${BASH_SOURCE[0]}")")/lib-app.inc.bash"
