#!/bin/bash -eu

#
# This is a utility to checkout git repositories in a shared location (e.g. under $HOME/gits-shared) and return the path to the checkout.
# It is designed to be used in other scripts to share git checkouts across different scripts and avoid multiple checkouts of the same repository.
# It also supports reloading the checkout and clearing it if it is invalid.
# Usage: git-shared-checkout [--reload|--clear] [--quiet] <repo_path> [--ref=<ref>]   | --version
#    eg: cat "$(git-shared-checkout https://github.com/Mac-H/ukko_gists)/readme.md"
#
# It needs to be possible to run without any other libraries (e.g. in a fresh docker image) and it should not produce any output on stdout except the path to the checkout (and error messages on stderr if needed).
#
GIT_SHARED_CHECKOUT_VERSION="0.0.5c"
[[ -z "${HOME:-}" ]] && SHARED_GIT_DIR="/usr/share/gits-shared"
[[ -n "${HOME:-}" ]] && SHARED_GIT_DIR="${HOME}/gits-shared"

function help_with_exit()
{
    local error_message="${1:-}"
    {
        [[ -n "$error_message" ]] && echo -e "${BOLD_RED_STDERR:-}⚠️  $error_message${NC_STDERR:-}"
        echo -e "Usage: $(basename "$THIS_EXE") [--reload|--clear] [--quiet] <repo_path> [--ref=<ref>]"
        echo -e "     --version=Show version : $GIT_SHARED_CHECKOUT_VERSION"
        echo -e "       <ref> = hash:###      -or-"
        echo -e "               branch:###    -or-"
        echo -e "               tag:###       -or-"
        echo -e "               hash-only:###  (No git history - only download the files)"
        echo -e "   eg: ${BOLD_BLUE_STDERR:-}cat \"\$($(basename "$THIS_EXE") https://github.com/Mac-H/ukko_gists)/readme.md\"${NC_STDERR:-}"
    } >&2

    if [[ -n "$error_message" ]]; then
        exit 1
    else
        exit 0
    fi
}

hadWarning='no'
function giveWarning()
{
    hadWarning='yes'
    [[ -n "$*" ]] && echo -e "${BOLD_RED_STDERR:-}⚠️  $*${NC_STDERR:-}" >&2
}


gitInfo_description=''
gitInfo_warning=''
##############################################
#
# Evalues git stored in:
#  * repo_fullDir
#
# Loads:
#  * gitInfo_description
#  * gitInfo_warning
#
# Also evaluates and triggers warnings based on:
#  * option_ref_type
#  * option_ref_value
#
function load_gitInfo()
{
    local hash=''
    local branch=''

    gitInfo_description=''
    gitInfo_warning=''


    if [[ "$option_ref_type" == 'hash-only' ]] ; then
        gitInfo_description="only:#${option_ref_value}"
    elif ! hash="$(git -C "$repo_fullDir" describe --always --dirty 2>/dev/null)"; then
        gitInfo_warning="<INVALID_GIT>"
    else
        branch="$(git -C "$repo_fullDir" branch --show-current 2>/dev/null || true)"
        gitInfo_description="${branch}@${hash}"

        if [[ "$option_ref_type" == "hash" ]] && [[ "$hash" != "$option_ref_value" ]]; then
            gitInfo_warning="Hash mismatch from expected"
        elif [[ "$option_ref_type" == "branch" ]] && [[ "$branch" != "$option_ref_value" ]]; then
            gitInfo_warning="Branch mismatch from expected"
        elif [[ "$hash" == *-dirty ]]; then
            gitInfo_warning="There are local changes"

        fi
    fi
}




option_is_reload='no'
option_is_erase='no'
option_is_quiet='no-unless-info'

option_ref_type=''
option_ref_value=''
option_repo_url=''
function load_params()
{
    [[ "${GIT_SHARED_CHECKOUT_QUIET:-}" == "yes" ]] && option_is_quiet='yes'

    local am_processing_options='yes'

    for arg in "$@"; do
        [[ -z "$arg" ]] && continue
        if [[ "$am_processing_options" == "yes" ]] && [[ "$arg" == '-'* ]]; then
            if [[ "$arg" == '--' ]] ; then
                am_processing_options='no'
            elif [[ "$arg" == '--version' ]]; then
                echo "$(basename "$THIS_EXE") version $GIT_SHARED_CHECKOUT_VERSION"
                exit 0
            elif [[ "$arg" == '--help' ]]; then
                help_with_exit
            elif [[ "$arg" == '--reload' ]]; then
                option_is_reload='yes'
            elif [[ "$arg" == '--clear' ]]; then
                option_is_erase='yes'
            elif [[ "$arg" == '--quiet' ]] || [[ "$arg" == '--quiet=yes' ]] ; then
                option_is_quiet='yes'
            elif [[ "$arg" == '--quiet=no' ]] ; then
                option_is_quiet='no'
            elif [[ "$arg" == '--ref='* ]]; then
                ref_arg="${arg#--ref=}"
                if [[ "$ref_arg" == '#'* ]]; then
                    ref_type='hash'
                    ref_value="${ref_arg#\#}"
                    giveWarning "Deprecated used of --ref=#${ref_value} :  Use --ref=hash:${ref_value} instead"
                elif [[ -n "$ref_arg" ]]; then
                    for x in hash hash-only branch tag ; do
                        if [[ "$ref_arg" == "$x:"* ]]; then
                            ref_type="$x"
                            ref_value="${ref_arg#"$x:"}"
                            break
                        fi
                    done

                    if [[ -z "$ref_type" ]]; then
                        help_with_exit "Invalid format for ${arg@Q} : Expected --ref=branch:<branch_name> or --ref=tag:<tag_name> or --ref=hash:<hash_value> or --ref=hash-only:<hash_value>"
                    fi
                fi
            else
                help_with_exit "Unknown option ${arg@Q}"
            fi
        elif [[ "$arg" == 'branch:'* ]]; then
            ref_type='branch'
            ref_value="${arg#branch:}"
            giveWarning "Deprecated used of ${arg} :  Use --ref=${arg} instead"
        elif [[ -z "$option_repo_url" ]]; then
            option_repo_url="$arg"
        else
            help_with_exit "Multiple repository URLs provided.  Already have ${option_repo_url@Q} but adding '${arg@Q}' is an error."
        fi
    done

    if [[ -z "$option_repo_url" ]] ; then
        help_with_exit "Repository URL not provided."
    fi
}

function main()
{
    ##############################################
    #
    # Load:
    #
    #    Value                 Default
    #    --------------------  ----------------
    #  * option_is_reload      'no'
    #  * option_is_erase       'no'
    #  * option_is_quiet       'no-unless-info'
    #  * option_ref_type       ''
    #  * option_ref_value      ''
    #  * option_repo_url       ''

    load_params "$@"


    ##############################################
    #
    # Load:
    #  * repo_friendlyName
    #  * repo_fullDir
    #
    repo_friendlyName="${option_repo_url%.git}"
    if [[ "$repo_friendlyName" == "https://"* ]] ; then
        repo_friendlyName="${repo_friendlyName##https://}"
    elif [[ "$repo_friendlyName" == "git@"*     ]] ; then
        repo_friendlyName="${repo_friendlyName##git@}"
    fi

    repo_fullDir="${SHARED_GIT_DIR%/}/${repo_friendlyName/://}"
    if [[ -n "$option_ref_type" ]] && [[ -n "$option_ref_value" ]]; then
        repo_fullDir="${repo_fullDir}_ref_${option_ref_type}_${option_ref_value}"
    fi

    [[ -n "$option_ref_type" ]] && repo_friendlyName+=" [$option_ref_type:$option_ref_value]"

    #########################
    #
    # Load:
    # * gitInfo_description
    # * gitInfo_warning
    #
    gitInfo_description=""
    gitInfo_warning=''
    if [[ ! -d "$repo_fullDir" ]] ; then
        gitInfo_description="EMPTY"
    elif [[ "$option_is_reload" == "yes" ]] || [[ "$option_is_erase" == "yes" ]] ; then
        do_with_check  rm -rf "$repo_fullDir"
        gitInfo_description="ERASED"
    else
        load_gitInfo "$repo_fullDir" "$option_ref_type" "$option_ref_value"
    fi

    {
        echo "ℹ️  !! -----------------------------------------------------"
        echo "ℹ️  !! * repo_friendlyName   = $repo_friendlyName"
        echo "ℹ️  !! * repo_fullDir        = $repo_fullDir"
        echo "ℹ️  !! "
        echo "ℹ️  !! * option_repo_url     = $option_repo_url"
        echo "ℹ️  !! * option_ref_type     = $option_ref_type"
        echo "ℹ️  !! * option_ref_value    = $option_ref_value"
        echo "ℹ️  !! "
        echo "ℹ️  !! * gitInfo_description = $gitInfo_description"
        echo "ℹ️  !! * gitInfo_warning     = $gitInfo_warning"
        echo "ℹ️  !! -----------------------------------------------------"
    } >&2


    #########################
    #
    # Clear if needed
    #
    if [[ "$option_is_erase" == "yes" ]]; then
        echo -e "$repo_caption: ${BOLD_BLUE_STDERR:-}ℹ️  $gitInfo_description${NC_STDERR:-} " >&2
        return 0
    fi

    if [[ "$gitInfo_warning" == "<INVALID_GIT>" ]]; then
        giveAlert "$repo_caption: $gitInfo_description -- Clearing"
        do_with_check rm -rf "$repo_fullDir"
    fi

    #########################
    #
    #
    #

    if [[ ! -d "$repo_fullDir" ]]; then

        mkdir -p "$repo_fullDir"
        cd "$repo_fullDir"

        [[ "$option_is_quiet" == 'no-unless-info' ]] && echo -e "Loading from cloud: ${BOLD_BLUE_STDERR:-}$repo_caption${NC_STDERR:-} into $repo_fullDir" >&2 && option_is_quiet='no'

        #########################
        #
        # Load the repo into $repo_fullDir
        #
        # Update:
        #  * gitInfo_description
        #  * gitInfo_warning
        #

        if [[ "$option_ref_type" == '' ]] ; then
             do_with_check git clone  "$option_repo_url" "$repo_fullDir"
        elif [[ "$option_ref_type" == 'branch' ]] ; then
             do_with_check git clone --branch "$option_ref_value" --depth 1 "$option_repo_url" "$repo_fullDir"
        elif [[ "$option_ref_type" == 'hash' ]] ; then
             do_with_check git clone  "$option_repo_url" "$repo_fullDir"
             do_with_check git -C "$repo_fullDir" checkout -q "$option_ref_value"
        elif [[ "$option_ref_type" == 'hash-only' ]] ; then
             url="https://${option_repo_url/:/}/archive/${option_ref_value}.zip"
             do_with_check wget -L -O "/tmp/${option_ref_value}.zip" "$url"
             do_with_check unzip "/tmp/${option_ref_value}.zip" -d "${repo_fullDir}"
        elif [[ "$option_ref_type" == 'tag' ]] ; then
             do_with_check git clone --branch "$option_ref_value"  --depth 1 "$option_repo_url" "$repo_fullDir"
        else
            giveAlert "Invalid ref type '$option_ref_type' for ref '$option_ref_value'"
            exit 1
        fi

        if [[ "$option_ref_type" != 'hash-only' ]] ; then

            [[ -f "${repo_fullDir%/}/.gitmodules" ]] && do_with_check git submodule update --init --recursive

            if [[ -f "${repo_fullDir%/}/.pre-commit-config.yaml" ]]; then
                if ! command -v pre-commit >/dev/null 2>&1 ; then
                    giveAlert "pre-commit not found in PATH.  Skipping pre-commit install for $repo_caption"
                else
                    pushd "$repo_fullDir" &>/dev/null
                    do_with_check pre-commit install >&2 # --install-hooks
                    echo "⚡ pre-commit hooks installed for $repo_caption" >&2
                    popd &>/dev/null
                fi
            fi
        fi
        load_gitInfo
    fi

    #################################################################################################################################
    # Summarise based on:
    #   * repo_friendlyName
    #   * gitInfo_description
    #   * gitInfo_warning
    #   * repo_fullDir
    #
    local repo_caption="$repo_friendlyName"
    [[ -n $gitInfo_description ]] &&  repo_caption+=" [$gitInfo_description]"
    [[ -n "$gitInfo_warning"   ]] &&  gitInfo_warning=" ${BOLD_RED_STDERR}⚠️  $gitInfo_warning${NC_STDERR}"

    if [[ "$option_is_quiet" != "yes" ]] || [[ -n "$gitInfo_warning" ]] || [[ "$hadWarning" == "yes" ]]; then
        echo -e "Using: ${BOLD_BLUE_STDERR:-}$repo_caption${NC_STDERR:-}$gitInfo_warning" >&2
        echo -e "       └── $repo_fullDir" >&2
    fi
    exit 0
}
function do_with_check()
{
    local caption="$*"

    local caption_decorated="$*"
    if [[ "$1" == '--caption='* ]]; then
        caption="${1#--caption=}"
        shift
    else
        caption_decorated="${BOLD_BLUE_STDERR:-}$caption${NC_STDERR:-}"
    fi
    local status=0
    local suffix=''

    echo -e "Running : ${caption_decorated}" >&2
    "$@" || status=$?
    if [[ "$status" == 0 ]] ; then
        true #echo -e "          -- OK" >&2
    else
        [[ "$status" == 1 ]] || suffix=" with status $status"
        echo -e "Ran    :${BOLD_RED_STDERR:-}$caption${NC_STDERR:-} -- Failed$suffix" >&2
        [[ "$caption" == "$*" ]] || echo -e "Command: ${BOLD_BLUE_STDERR:-}$*${NC_STDERR:-}" >&2
        exit 1
    fi
}

function do_install_directly()
{
    local INSTALL_DIR="${HOME%/}/.local/bin" ; [[ "$EUID" -eq 0 ]] && INSTALL_DIR="/usr/local/bin"
    local exe_path="${INSTALL_DIR%/}/$EXE_NAME"
    if [[ "$exe_path" == "$THIS_EXE" ]]; then
        echo "✅  This is already currently installed to $exe_path"
        return 0
    fi
    if ! cp "$THIS_EXE" "$exe_path"; then
        echo "❌  Failed to copy $THIS_EXE to $exe_path"
        return 1
    fi

    if ! [[ ":$PATH:" == *":$INSTALL_DIR:"* ]]; then
        echo "⚠️  '$EXE_NAME' installed to ${INSTALL_DIR@Q} but it is NOT in PATH.  Please add ${INSTALL_DIR@Q} to your PATH environment variable." >&2
        return 1
    fi
     echo "✅  '$EXE_NAME' installed successfully to ${INSTALL_DIR@Q} and is available in PATH"
}

THIS_EXE="$(readlink -m "${BASH_SOURCE[0]}")"
EXE_NAME="$(basename "$THIS_EXE")"


[[ -t 2 ]] &&  BOLD_BLUE_STDERR="\033[1;34m" && BOLD_RED_STDERR='\033[1;31m' &&  NC_STDERR='\033[0m' # Color codes for terminal output

if [[ "${1:-}" == '--install' ]]; then
    do_install_directly
elif [[ "${1:-}" == "--remove" ]] || [[ "${1:-}" == "--uninstall" ]]; then
    (sleep 0.5 && rm -f "$THIS_EXE" && echo "Removed $THIS_EXE") &
else
    main "$@"
fi
