#!/usr/bin/env bash
set -eu
############################################################
# This is basically equivalent to:
#
# docker run -it -v "$(pwd)":/app "ubuntu:24.04" bash
#
#    root@ab92bb7bcd54:/# cd app
#    root@ab92bb7bcd54:/app# do-full-install-from-blank.sh
#
############################################################

APP_VERSION="0.0.1"
APP_DESCRIPTION="Runs a command on a docker image with some supportive extras (e.g. copying ssh keys, mounting the app directory, etc.)"

function app_help()
{
    echo -e "Usage : ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} <docker-images> [options] -- [cmd to run] [parameters for cmd..]${COLOUR[OFF_USED]:-}"
    echo ""
    echo "Options:  <docker-images>    : Docker images to use for testing"
    echo "                               (e.g. 'ubuntu:22.04' -or 'ubuntu:22.04,ubuntu:24.04,ubuntu:26.04,ubuntu:latest')"
    echo ""
    echo "          --exit=<value>     : yes        = Always exit after running the command"
    echo "                               no         = Don't exit automatically after running the command"
    echo "                               on-success = Stay in docker if the command fails - otherwise exit"
    echo "                                            (Default is 'on-success' for a single image, otherwise 'yes')"
    echo ""
    echo "          --keys-dir=<dir>   : The directory containing SSH keys that the container may use"
    echo "                               (Default: ~/.ssh/)"
    echo "          --workspace=<dir>  : The directory to be mapped to '/workspace' inside the container"
    echo "                               (Default: $(displayPath "$ORIG_PWD"))"
    echo "          --apt-get=yes      : Perform \`apt-get update\` and steps"
    echo ""
    echo "          --dry-run          : Does a dry-run without actually executing the command (useful for experiments)"
    echo ""
    echo -e "Example  : ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} ubuntu:22.04 --exit=no  cat /etc/os-release${COLOUR[OFF_USED]:-}"

    readarray -t _builders < <(find "$ORIG_PWD" -mindepth 1 -maxdepth 1 -type f -executable -name '*do-build*')

    for cmd in "${_builders[@]}" ; do
        echo -e "           ${COLOUR[VIVID_BLUE_USED]:-}${CMD_AS_DISPLAY} ubuntu:22.04,ubuntu:24.04,ubuntu:26.04,ubuntu:latest  -- ./${cmd##*/} --with-tests${COLOUR[OFF_USED]:-}"
    done
}

function app_load_param_defaults()
{
    option_docker_images=''
    option_exit='default'
    option_workspace="$ORIG_PWD"
    option_keys_dir='' ;   [[ -n "${HOME:-}" ]] && option_keys_dir="${HOME%/}/.ssh/"
    option_dry_run=''
    option_apt_get='no'
    option_cmd_to_run=()
}

function app_load_param_direct_value()
{
    [[ -z "${option_docker_images:-}" ]] && option_docker_images="$1" && return 0

    option_cmd_to_run+=("$1")
    return 0
}

function app_load_param_option_name_value()
{
    [[ "$1" == '--docker-images=' ]]           && option_docker_images="$2"  && return 0
    [[ "$1" == '--workspace='     ]]           && option_workspace="$2"      && return 0
    [[ "$1" == '--keys-dir='      ]]           && option_keys_dir="$2"       && return 0
    [[ "$1" == '--dry-run'        ]]           && option_dry_run='yes'       && return 0
    param_choose_yes_no "exit"       "$1" "$2" && option_exit="$2"           && return 0
    param_choose_yes_no "!apt-get"   "$1" "$2" && option_apt_get="${2:-yes}" && return 0
    return 1
}

function app_run()
{
    echo "APPS_NAME: ${APPS_NAME:-}  (Version: ${APP_VERSION:-}, Description: ${APP_DESCRIPTION:-})"
    IFS=',' read -ra docker_images_array <<< "$option_docker_images"

    [[ "${#docker_images_array[@]}" == 0 ]] && do_errorExitWithSuggestion "Docker images not specified"

    if [[ "$option_exit" == 'default' ]] ; then
        if [[ "${#docker_images_array[@]}" == 1 ]] ; then
            option_exit='on-success'
        else
            option_exit='yes'
        fi
    fi

    local results=()
    local overall_result_code=0
    local index=1
    for img in "${docker_images_array[@]}" ; do
        echo "Running image[$index]: $img"
        local this_result=0
        docker_run "$img" || this_result="$?"

        if [[ "${option_dry_run:-}" == 'yes' ]] ; then
            _msg="ℹ️  Docker dry-run       : $(quoteIfNeeded "${docker_params[@]}")"
        elif [[ "$this_result" == 0 ]]; then
            _msg="✅  Docker run succeeded : $img" "$(displayPath "$option_workspace")" "$(quoteIfNeeded "${local_cmd_to_run[@]}")"
        else
            _msg="❌  Docker run failed    : $(quoteIfNeeded "${docker_params[@]}")"
            [[ "$this_result" != 1 ]] && _msg+="  [Exit code: $this_result]"
        fi

        [[ "$this_result" == 0 ]] || overall_result_code="$this_result"

        results+=("$_msg")
        ((index++))
    done
    echo ""
    {
        echo "Overview:"
        for msg in "${results[@]}" ; do
            echo "$msg"
        done
    } >&2
    [[ "$option_dry_run" != 'yes' ]] && ! command -v docker &> /dev/null && do_errorExitWithSuggestion "Docker is not installed or not in PATH. Please install Docker to use this app."
    return "$overall_result_code"
}

function docker_run()
{
    local docker_image="$1"

    option_workspace="$(realpath -m "${option_workspace}")"

    docker_params=(docker run -it)

    ######
    #
    tmpdir_for_startup_script="$(mktemp -d '/tmp/runWithinImage_XXXX')"
    cp -a "${EXE_DIR%/}/_internalUse/_in_docker_startup.sh" "${tmpdir_for_startup_script}/_startup.sh"

    if [[ "${option_apt_get}" == "yes" ]] ; then
       {
            echo "#!/usr/bin/env bash"
            echo "set -eu"
            echo "apt-get update"
            echo "apt-get install -y git"
            echo "git config --global --add safe.directory /workspace#"
            echo "cat /etc/os-release"
        } | create_executable_run_script "pre-0001-apt-get-update-and-install-git.sh"
    fi

    docker_params+=("-v" "${tmpdir_for_startup_script%/}/:/startup")
    if [[ -n "${option_keys_dir:-}" ]]; then
        mkdir -p "${tmpdir_for_startup_script}/ssh_keys"
        cp -a "${option_keys_dir%/}/"* "${tmpdir_for_startup_script}/ssh_keys/"
    fi
    #
    ######
    [[ -n "${option_workspace:-}"  ]] && docker_params+=("-v" "${option_workspace%/}/:/workspace")
    docker_params+=("${docker_image}")
    docker_params+=("bash" "/startup/_startup.sh" "--exit=${option_exit}")
    local_cmd_to_run=()
    for arg in "${option_cmd_to_run[@]}" ; do
        if [[ "$arg" == "${option_workspace%/}/"* ]] ; then
            arg="/workspace/${arg#"${option_workspace%/}"/}"
        fi
        local_cmd_to_run+=("$arg")
    done

    [[ "${#local_cmd_to_run[@]}" -gt 0 ]] && docker_params+=("run:" "${local_cmd_to_run[@]}")

    echo "             -> $(quoteIfNeeded "${docker_params[@]}")"

    [[ -n "${option_dry_run:-}" ]] && echo "Dry-run mode enabled, not executing the docker command." && return 0

    local result=0
    "${docker_params[@]}" || result="$?"

    echo "ℹ️  Returned from docker with exit code: $result" >&2

    rm -rf "${tmpdir_for_startup_script}"

    return "$result"
}

function create_executable_run_script()
{
    local script_path="${tmpdir_for_startup_script%/}/${1}"

    cat > "$script_path"

    chmod +x "$script_path"
}
source "$(dirname "$(realpath -m "${BASH_SOURCE[0]}")")/../lib-app.inc.bash"
